	/*instance_deactivate_layer("Collisions");
	instance_activate_object(oPlayer);
	instance_activate_object(oAtuin);
	instance_activate_object(oCam);
	instance_activate_object(oGuide);
	var _vx = camera_get_view_x(view_camera[0]);
	var _vy = camera_get_view_y(view_camera[0]);
	var _vw = camera_get_view_width(view_camera[0]);
	var _vh = camera_get_view_height(view_camera[0]);
	instance_activate_region(_vx -400, _vy -2000, _vw + 400, _vh + 2000, true);